#!/usr/bin/env bash
# This script lists all databases in MongoDB

mongo --quiet --eval "db.adminCommand('listDatabases').databases.forEach(function(db) { print(db.name + '\t' + db.sizeOnDisk/1024/1024 + 'MB'); })"
